### ISSUE TITLE
Content under "Failed to load. Retry?" flickers while "Retry?" button is clicked

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1080]
**Wallet version or commit SHA:**
0f2951a

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
At least one wallet imported to the app
Disconnect internet connection

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Retry?" button several times in a row

Sometimes it happens on a first click, sometimes not. Easiest way to reproduce this issue is to click "Retry?" several times in a row.

**Screenshots/Video:**
![flickering_under](https://user-images.githubusercontent.com/8177587/39828701-48932e60-53bc-11e8-82a3-414409c3f8ca.gif)

**Comment by mhuggins** [comment]
I was thinking "this definitely didn't happen to me!"  Then I saw you wrote:

> Click on "Retry?" button several times in a row

Now it makes more sense. 😄

**Comment by drptbl** [comment]
@mhuggins It happens on first click sometimes, but it's hard to reproduce this way. While clicking several times in a row - easy peasy 🎉.

**Comment by alexhulbert** [comment]
@drptbl This issue is currently pending Quality Assurance. I think this should be fixed by PR #1177, but I'm not 100% sure. I tried disconnecting myself from the internet and spamming the retry buttons. It seems as though the token balance flickering has been fixed by the fact that the endpoint requests don't hang when connecting to localhost.

**Comment by drptbl** [comment]
@alexhulbert Looks like this is still an issue.

Just login to the wallet when disconnected from the internet and try to click "Retry". You can still experience flickering.


![flicker2](https://user-images.githubusercontent.com/8177587/41008636-5b359582-692c-11e8-900e-3a0823f7ee90.gif)

**Comment by drptbl** [comment]
Fixed! Thank you.
