### ISSUE TITLE
NEON-wallet doesn't show balance - after almost 1 day...

### ISSUE THREAD

**Issue by ineptio007** [CityOfZion/neon-wallet#152]
Yesterday 
![clipboard01](https://user-images.githubusercontent.com/31584436/30001315-5c133f7a-908a-11e7-9e00-271673a46e30.jpg)
![clipboard02](https://user-images.githubusercontent.com/31584436/30001314-5c12e08e-908a-11e7-8880-97382446067b.jpg)
![clipboard03](https://user-images.githubusercontent.com/31584436/30001316-5c144e10-908a-11e7-9b6b-94a2c11e2987.jpg)

I transferred 7 NEO from Bittrex to the NEON-wallet. But until now, I cannot see them appearing in the wallet.

My public address is AG69WGpnHB3ZNxhKCxJ9mX9HaxkErnYfVc and when I check my address at [https://neotracker.io/address/AG69WGpnHB3ZNxhKCxJ9mX9HaxkErnYfVc](url) , I can clearly see what my balance in the NEON-wallet should be - 7 NEO. 

As you can see on the print from Bittrex, I already sent them to the NEON-wallet yesterday (TxId: b3815251a52bc9e5f5149f2199fe7b3f58114eff75bd7a4ddc6de9bb15d477f5) but still nothing there...

I am using my home-network so there is no special firewall present... I use the latest NEON-wallet and even tried the previous version, but it doesn't make a difference.

Can somebody help me?

**Comment by trashcore** [comment]
i have exactly the same problem. I noticed that when i login into neotracker.io they ask me for a password. But when i login into Neon APP , only asks for private key (WIF). Please help

**Comment by Ejhfast** [comment]
Try 0.0.5? This seems like some sort of connectivity issue, your balance is showing on the API: 

http://api.neonwallet.com/v2/address/balance/AG69WGpnHB3ZNxhKCxJ9mX9HaxkErnYfVc

^ is what wallet uses to display balance...

**Comment by ineptio007** [comment]
Hello,

Excuse me.

'Try 0.05' where? In the Neonwallet there is no possibility to do so.

I have noticed that it does appear in https://neotracker.io/wallet but can I use this wallet to send & receive tokens as well?

Tim

Ethan Fast <notifications@github.com> wrote:
Try 0.0.5? This seems like some sort of connectivity issue, your balance is showing on the API:
http://api.neonwallet.com/v2/address/balance/AG69WGpnHB3ZNxhKCxJ9mX9HaxkErnYfVc
^ is what wallet uses to display balance...
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CityOfZion/neon-wallet","title":"CityOfZion/neon-wallet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CityOfZion/neon-wallet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ejhfast in #152: Try 0.0.5? This seems like some sort of connectivity issue, your balance is showing on the API: \r\n\r\nhttp://api.neonwallet.com/v2/address/balance/AG69WGpnHB3ZNxhKCxJ9mX9HaxkErnYfVc\r\n\r\n^ is what wallet uses to display balance...\r\n"}],"action":{"name":"View Issue","url":"https://github.com/CityOfZion/neon-wallet/issues/152#issuecomment-327687384"}}}

**Comment by Ejhfast** [comment]
New release 0.0.5: https://github.com/CityOfZion/neon-wallet/releases/tag/0.0.5

**Comment by ineptio007** [comment]
I installed 0.05 but it still doesn't work.
If I can use the  https://neotracker.io/wallet to send & receive tokens, I will try to use this one. It is probably better...

**Comment by danshao** [comment]
Devs, this issue is confirmed in 0.0.5. Not showing any balance in NEON at all. 35 confirmations.

**Comment by stevesbrain** [comment]
Quoting another user:

```Neon's server needed a rebuild due to some behind-the-scenes API changes. This is in progress now, so everything should be working again shortly.

Visit and read the #support channel on Slack for updates.```

**Comment by totalvm** [comment]
There was an issue with the nodes, should be solved now

**Comment by ineptio007** [comment]
Nope. For me it is still the same when I use the NEON-wallet (even with the newest version).

**Comment by stevesbrain** [comment]
@ineptio007 Still should head on over to Slack for support :)

**Comment by hipflask01** [comment]
im using neon wallet 0.0.7 and i have the same issue. my coins are showing in wallett https://neotracker.io/wallet but not in neon app after about 3 hours

**Comment by ineptio007** [comment]
I quit using it.

NEOTRACKER.IO is much better.

December 18, 2017 11:25:43 AM CET hipflask01 <notifications@github.com> wrote:
im using neon wallet 0.0.7 and i have the same issue. my coins are showing in wallett https://neotracker.io/wallet but not in neon app after about 3 hours
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CityOfZion/neon-wallet","title":"CityOfZion/neon-wallet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CityOfZion/neon-wallet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hipflask01 in #152: im using neon wallet 0.0.7 and i have the same issue. my coins are showing in wallett https://neotracker.io/wallet but not in neon app after about 3 hours"}],"action":{"name":"View Issue","url":"https://github.com/CityOfZion/neon-wallet/issues/152#issuecomment-352385759"}}}
