### ISSUE TITLE
Neon cannot send total amount of GAS 

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neon-wallet#2285]
There is a calculation issue when determining the maximum amount of GAS that can be sent after subtracting the required fee. The "Max" button will always show an amount plus fee less 0.06078673 GAS (and you can't manually override this maximum amount). So when the user sends the transaction after hitting the "Max" button they will always be left with 0.06078673 GAS in the wallet that cannot be transferred.

**Comment by gsmachado** [comment]
Yes, I can confirm this issue as well. It's still present in 2.9.4.

**Comment by comountainclimber** [comment]
NOTE: We should also include a conditional warning that renders in the UI if the user is about to send all of their GAS out of wallet

**Comment by jseagrave21** [comment]
Can this issue be closed? I think it has been fixed.

**Comment by hal0x2328** [comment]
I don't think it's fixed. I've encountered a few users with the problem since this issue was closed and this was just posted to Reddit: https://www.reddit.com/r/NEO/comments/1daerm3/cannot_send_gas_to_another_wallet/
