### ISSUE TITLE
Cant login to Neon Wallet

### ISSUE THREAD

**Issue by tgtcph** [CityOfZion/neon-wallet#436]
Have 11 NEOs in my Neon wallet, have the KeyStore file extracted, the Private key saved and cant login to my wallet.
I tried it on version 0.0.6 and 0.0.7 as well. It keeps saying my private key is not valid, also keeps sayin my keystore file is not valid.

What happened?
Please help me to fix this issue.

Thanks and happy holidays!

**Comment by tgtcph** [comment]
Ah and here is my address:
AJwBzhSqAW38rvvrg9A68RpEdYiKrk9akE

I checked it on NeoTracker and my balance is on the wallet I just cant reach it. Also tried to use my JSON file NeoTracker to access to the wallet, but says its not valid?!

Thanks for the headsup on this situation!

**Comment by Satoshinaire** [comment]
This was resolved in the Discord chat. The issue was a typo.

**Comment by Johnnyo808** [comment]
Im having the same issues my private key and encrypted key on my login tells me error not a valid key. I downloaded the new update and still happens. How can i fix this please help.
