### ISSUE TITLE
"Transaction failed" updated everything. cant send neo or claim gas for 2 months now :(

### ISSUE THREAD

**Issue by Birkii** [CityOfZion/neon-wallet#529]
this is probably a common problem. But its getting frustrating! what can be done? I cant send my neo out of my neon wallet, nor can i claim my gas. updated to 0.0.9 wallet. and 1.1.1 on ledger. Still continues to say "Transaction failed" over an over. Any help would be appreciated !!!

**Comment by stevesbrain** [comment]
Hard to say without more info. I too am using Neon with Ledger Nano S on 0.0.9 and 1.1.1 - no issue. Are you signing *both* transactions when claiming gas? Is the USB cable dodgy at all? Any anti-virus software active on the system that may be interfering? Do you use the Ledger for other currencies without issue?

**Comment by Birkii** [comment]
Hi. It doesn't go past the first sign tx for claiming gas. I send ltc dgb etc perfectly fine... so don't think its the usb cable. Don't have any antivirus on my laptop. Maybe I should try another device? ...... last 2 days the "sign now" doesn't even come up on my ledger.... it's extremely slow

**Comment by Birkii** [comment]
Tried uninstalling and reinstalling both apps aswell....

**Comment by morrow95** [comment]
For what its worth I just installed 0.0.9 for Windows and uninstalled then reinstalled the latest NEO for Ledger Blue to make sure I had the latest on there.  I just tried to claim GAS and got a whole bunch of red error alerts for other tokens and on top of that my GAS claim failed even after signing both transactions.

Is this on the software side of things or the actual chain?  Either way this is not normal behavior compared to what I am used to.

**Comment by Birkii** [comment]
I'm getting the red error alerts too. A heap of them. Another person has told me to try use WIF and click the private key button to access them and try send that way.... I will give that a go soon......

**Comment by morrow95** [comment]
I logged out of the Neon and then back in and tried again... the GAS transfer worked this time.  I also received NEO as well a few minutes later without any problems.  With that said, I still got a whole bunch of the red error alerts for the 'other' tokens about not being able to find a balance (I am assuming because they are zero).  Sounds like some simple logic needs coded in to the wallet for that.

**Comment by Birkii** [comment]
Have you tried sending neo out of your neon wallet to a exchange?

**Comment by morrow95** [comment]
@Birkii  I sent GAS to an exchange and then a few minutes later sent NEO to my wallet.

**Comment by Birkii** [comment]
I ended up using the neotracker.io wallet

**Comment by sandeeppoonia** [comment]
I am also having the same issue. Tried 0.0.9, 0.1.0 and 0.1.1 wallet. Please help.

**Comment by Birkii** [comment]
try using the recovery site to get the WIF, and using the WIF to send the funds out.

https://coranos.github.io/neo/ledger-nano-s/recovery/

^ I used this link(OFFLINE) to get the wif... the i used the neotracker.io wallet to move my funds. 

Make sure your not connected to the internet when you put your passphrase in to get your WIF.

**Comment by d4designstudios** [comment]
I am currently having the same issue trying to claim gas.

**Comment by AndyReach** [comment]
I am having also the same issue since a few hours with Claiming GAS. Before this I had never issues claiming GAS. Using NEON Wallet version 0.1.1. Any help appreciated.

**Comment by ggaabe** [comment]
Having the same issue. Gas shows up on neotracker but show up unclaimed on the 0.1.1 wallet, and then transaction fails when claim is attempted.

**Comment by quangate** [comment]
i am having same issue here using Using NEON Wallet version 0.1.1. cannot claim gas nor can withdraw neo out of wallet to exchanges or different wallet . it just says transaction fails you do anything .help appreciated

**Comment by przemas466** [comment]
Hi  we are more and more I have the same problem  with NEON Wallet version 0.1.1. cannot  send  neo and claim gas _ transaction failed do sombody know allready answer what going on?

**Comment by AndyReach** [comment]
Lots of users have the same issue today https://www.reddit.com/r/NEO/comments/6tl7ej/support_wallet_questions_neoneonweb_hardware/

**Comment by Liurik** [comment]
i have the same problem using NEON Wallet version 0.1.1

**Comment by AndyReach** [comment]
Hi guys the issue has been solved by Developers I now can claim again GAS and sending out NEO from NEON Wallet with my Ledger Nano S. Thanks guys

**Comment by Liurik** [comment]
ok now)))

**Comment by Thebigmeany** [comment]
this is still not working for me. "sending neo to yourself" "transaction failed"

**Comment by stevesbrain** [comment]
@Thebigmeany Are you behind a proxy/internet filter? Are you using the latest version of the software?

**Comment by bbrkhan** [comment]
I had issues too, but then realized I was using a VPN. Disabling it made everything smooth.

**Comment by iotaaa** [comment]
Hi guys, I'm stuck on the same problem. I have:
updated NEON on desktop to latest version
deleted and reinstalled NEO on Ledger

I cant claim GAS or send NEO. Transaction failed. I have tried restarting PC. Tried various WiFi routes. Still no luck. Can we get an update on this? Thanks

**Comment by dafrench57** [comment]
Hi !
I've got the same issue... I'm trying to send ZPT from NEON 0.1.2 (using ledger to unlock wallet) to exchange but I've got a "Transaction Failed" every time... (I've got GAS)
Can we have an update about the issue ? Regards

**Comment by iotaaa** [comment]
@dafrench57 I think you have to update neon to latest wallet.. I saw on discord they released a new version yesterday. I will try tomorrow.

**Comment by dafrench57** [comment]
@iotaaa Neon 0.1.2 is the latest version dude :) ! Just check the release page

**Comment by AndyReach** [comment]
Update Neon 0.1.2 works perfect ;-)

**Comment by shivamp1** [comment]
Hi Guys, Ive got the latest version of neon wallet, Ive just uninstalled and reinstalled it as well, but it doesnt allow me to sent tokens out of my ledger nano. Last week it had allowed me to take out Neo but no Gas, no DBC, no RPX and no QLC, please help

**Comment by Laurentius26** [comment]
@shivamp1 , same issue here. Latest Neon wallet version 0.1.2 with Ledger Nano. Sending GAS is not working. Very anoying as I have 10 GAS, a lot of money. :-( Huge bugger. Any help I could use as well.

**Comment by SirMaggot** [comment]
To send GAS, try to decrease the amount by 1 digit. (If you have 0.87654 GAS, send 0.87653)

**Comment by shivamp1** [comment]
Thanks but unfortunately reducing the number of digits does not appear to work. Could it be an issue with Macbooks?

**Comment by SirMaggot** [comment]
@shivamp1 Sorry to hear that it didn't work for you. I just had 4 transactions failing from my Ledger 
(Win 10), but after pressing "Max" and reduce it by 1 digit, the transaction worked.
I did logout from Neon (v0.12) a couple of times.

**Comment by anfn101** [comment]
Try reinstalling both Ledger Neo app and Neon wallet. Make sure your firewall is not the issue. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.

**Comment by leafcutterant** [comment]
Same problem here. Can't send NEO.

@anfn101, software error occur due to mistakes in code. I can't see how this is not a place to discuss it.

**Comment by shivamp1** [comment]
So I finally found a resolution.
I uninstalled and reinstalled the neo app on my ledger which allowed me to withdraw rpx, dbc and qlc after a few attempts.
Gas was still stuck and I managed to derive something someone else posted on another forum.
So looks like sending extremely small fractions of gas and gradually titrating up was the solution to my problem. 
Thanks to all those who tried to help.

**Comment by Cryptomanifest** [comment]
I'm at a loss.... this is happening to me. Have not used my Ledger + Neon for NEO for a couple months. Went in and updated all Firmware & apps on Ledger & Neon Wallet 0.2.4 and still nothing. Can not send. Transaction Failed : Network Error every time I try and send. Can not claim gas either. Running on the same system always, same settings, etc. Even tried another machine & a new ledger , same issues....

I have never had any issues since Neon Wallet + Ledger came out. Now I need to move coins and cant

**Comment by stevesbrain** [comment]
@Cryptomanifest Have you tried with a different blockchain explorer?

**Comment by Cryptomanifest** [comment]
@stevesbrain yes, switched between them all in settings on Neon Wallet. 

When I press F12 i see ERR_CONNECTION_TIMED_OUT at the bottom linking to ex seed.aphelion.org, etc, failed to load resource. Not sure if that helps, but lots of those errors.

**Comment by stevesbrain** [comment]
@Cryptomanifest Is there any firewall on your system or network? I've seen the same issue where people have tried to claim at work, and failed, due to network firewall. Is this possible in your circumstance?

**Comment by Cryptomanifest** [comment]
@stevesbrain at home only, always the same laptop for crypto only. I even turned the firewall & antivirus off and nothing. Called the ISP (Spectrum) and they assured me every port was open in and out. 8080, etc. No clue at this point. Never had this happen, been a couple months since I logged in. Always worked. Even sent other coins from other wallets to test, etc.

**Comment by stevesbrain** [comment]
@Cryptomanifest The things I'd be thinking of trying:

- Different USB cable
- Different computer
- Through a VPN (to eliminate your ISP blocking the ports, which they do even if they say they don't - they're mandated to block certain ports, and there's a list of "suggested" ports that many ISP's block)
- See if the same issue exists without a Ledger - just using Neon with some testnet Neo

**Comment by Cryptomanifest** [comment]
@stevesbrain tomorrow I'll test at a friends house / wifi see what happens

Appreciate your time. Thank you very much.

**Comment by stevesbrain** [comment]
No worries @Cryptomanifest - good luck :)

**Comment by gfijrb** [comment]
still can not send my coins((( what to do?
